export const GET_EMPLOYEES_DATA_REQUEST=' GET_DATA_REQUEST';
export const GET_EMPLOYEES_DATA_SUCCESS=' GET_DATA_SUCCESS';
export const GET_EMPLOYEES_DATA_ERROR=' GET_DATA_ERROR';


export const ADD_EMPLOYEES_DATA_REQUEST=' ADD_DATA_REQUEST';
export const ADD_EMPLOYEES_DATA_SUCCESS=' ADD_DATA_SUCCESS';
export const ADD_EMPLOYEES_DATA_ERROR=' ADD_DATA_ERROR';


export const UPDATE_EMPLOYEES_DATA_REQUEST=' UPDATE_DATA_REQUEST';
export const UPDATE_EMPLOYEES_DATA_SUCCESS=' UPDATE_DATA_SUCCESS';
export const UPDATE_EMPLOYEES_DATA_ERROR=' UPDATE_DATA_ERROR';


export const DELETE_EMPLOYEES_DATA_REQUEST=' DELETE_DATA_REQUEST';
export const DELETE_EMPLOYEES_DATA_SUCCESS=' DELETE_DATA_SUCCESS';
export const DELETE_EMPLOYEES_DATA_ERROR=' DELETE_DATA_ERROR';
