export const GET_EMPLOYEES_DATA_REQUEST='GET_EMPLOYEES_DATA_REQUEST';
export const GET_EMPLOYEES_DATA_SUCCESS='GET_EMPLOYEES_DATA_SUCCESS';
export const GET_EMPLOYEES_DATA_ERROR='GET_EMPLOYEES_DATA_ERROR';


export const ADD_EMPLOYEES_DATA_REQUEST='ADD_EMPLOYEES_DATA_REQUEST';
export const ADD_EMPLOYEES_DATA_SUCCESS='ADD_EMPLOYEES_DATA_SUCCESS';
export const ADD_EMPLOYEES_DATA_ERROR='ADD_EMPLOYEES_DATA_ERROR';


export const UPDATE_EMPLOYEES_DATA_REQUEST='UPDATE_EMPLOYEES_DATA_REQUEST';
export const UPDATE_EMPLOYEES_DATA_SUCCESS='UPDATE_EMPLOYEES_DATA_SUCCESS';
export const UPDATE_EMPLOYEES_DATA_ERROR='UPDATE_EMPLOYEES_DATA_ERROR';


export const DELETE_EMPLOYEES_DATA_REQUEST='DELETE_EMPLOYEES_DATA_REQUEST';
export const DELETE_EMPLOYEES_DATA_SUCCESS='DELETE_EMPLOYEES_DATA_SUCCESS';
export const DELETE_EMPLOYEES_DATA_ERROR='DELETE_EMPLOYEES_DATA_ERROR';


export const SEARCH_EMPLOYEES_DATA_REQUEST='SEARCH_EMPLOYEES_DATA_REQUEST';
export const SEARCH_EMPLOYEES_DATA_SUCCESS='SEARCH_EMPLOYEES_DATA_SUCCESS';
export const SEARCH_EMPLOYEES_DATA_ERROR='SEARCH_EMPLOYEES_DATA_ERROR';
